apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.cluster.name }}-0
  namespace: {{ .Release.Namespace }}
  labels:
    tier: patroni-citus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    application: {{ .Values.cluster.application }}
    cluster-name: {{ .Values.cluster.name }}
    citus-group: "{{ .Values.coordinator.group }}"
    citus-type: {{ .Values.coordinator.type }}
subsets: []

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.name }}-0
  namespace: {{ .Release.Namespace }}
  labels:
    tier: patroni-citus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    application: {{ .Values.cluster.application }}
    cluster-name: {{ .Values.cluster.name }}
    citus-group: "{{ .Values.coordinator.group }}"
    citus-type: {{ .Values.coordinator.type }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.name }}-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    tier: patroni-citus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    application: {{ .Values.cluster.application }}
    cluster-name: {{ .Values.cluster.name }}
    citus-group: "{{ .Values.coordinator.group }}"
    citus-type: {{ .Values.coordinator.type }}
    role: master
spec:
  type: {{ .Values.service.type }}
  selector:
    application: {{ .Values.cluster.application }}
    cluster-name: {{ .Values.cluster.name }}
    citus-group: "{{ .Values.coordinator.group }}"
    citus-type: {{ .Values.coordinator.type }}
    role: master
  ports:
  - name: {{ .Values.cluster.name }}-coordinator
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}