apiVersion: v1
kind: Secret
metadata:
  name: citus-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    tier: patroni-citus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    application: {{ .Values.cluster.application }}
    cluster-name: {{ .Values.cluster.name }}
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  superuser-username: cG9zdGdyZXM=
  citus-database: Y2l0dXM=
  replication-password: cmVwLXBhc3M=
  replication-username: c3RhbmRieQ==