apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  labels:
    tier: patroni-citus
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}